### ISSUE TITLE
Create all steps of the MVP

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/tenants2#104]
These are the broad strokes of what needs to be implemented:

- [x] Splash page (not logged in)
- [x] Onboarding step 1 (name and address)
- [x] Onboarding step 2 (housing issues)
- [x] Onboarding step 3 (lease type)
- [x] Onboarding step 4 (phone number, password)
- [x] Create the user's account on the back-end (#105)
- [x] Welcome modal (#105)
- [x] "Why mail a certified letter of complaint?" page (#108)
- [x] Complete your issues checklist (#109, #114)
- [x] Add access dates (#130)
- [x] Obtain landlord address (#135)
- [x] Review the letter of complaint (#138, #139, #141)
- [x] Confirmation (#143)
