### ISSUE TITLE
Fully internationalize NoRent.org

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/tenants2#1384]
Ok, we're ramping up i18n for the NoRent site, which resides in this codebase, so this is a big priority now.

This is a subset of #12, in that we're not going to internationalize parts of the codebase that are only used by the JustFix.nyc side of the platform.

## Out of scope

* We don't currently engage NoRent.org on TextIt flows, so we don't need to worry about it right now.  (If/when we do, when we create users in TextIt, we'll want to set their TextIt locale to their locale in the TP.)

## To do

- [x] We've been using LinguiJS with Crowdin on Who Owns What for a while now (see https://github.com/JustFixNYC/who-owns-what/pull/186) and it works great, so we'll probably go with that here too. **Update:** Did this in #1376.

- [x] We'll need to run (and document) Django's `makemessages`/`compilemessages` in the codebase to make sure that everything on the Django-side can be internationalized. **Update:** done in #1386.

- [x] Need to figure out what to do about our Mapbox and NYC GeoSearch autocompletes.  Mapbox appears to support localization but I'm not sure about NYC GeoSearch.  And even though Mapbox supports localization, I'm not actually sure if it'll be easy to use it, since we ultimately want the addresses in English for Lob/the landlord, and storing them in the user's locale _and_ English will make Mapbox a requirement (not just a nice-to-have), will make it hard/impossible to specify addresses Mapbox/our algorithm might not know about, and other things.  Sooo, really 🤞 that Spanish speakers will be OK with English city names and street addresses.  **Update:** Thankfully we don't need to worry about localizing city and street names, so we can just keep Mapbox on `en`.

- [x] Ok, even though we don't need to internationalize street/city names, we should probably make the Mapbox city/state autocomplete widget use the Spanish name of the state, since we're doing that everywhere else in the app.  **Update:** fixed in #1394.

- [x] Support the viewing and [(eventual)](#1247) asynchronous sending of the letter and associated emails in their preferred locales:
  - [x] Add a language preference field to the `JustfixUser` model that can be set during onboarding based on the request locale (#1472)
  - [x] Ensure the email and letter to the landlord are in English, while the email to the user is in their preferred locale (#1473).
  - [x] Design and implement UX on the website to ensure that the user can read the letter in both their preferred locale _and_ in English (#1502).

- [x] We'll have to figure out how we want to localize content in the `common-data` directory. **Update:** fixed by #1383.

- [x] Make sure dates on the front-end (e.g. "July 1") are localized (#1494, #1495).

- [x] We'll have to figure out how to localize content we pull from Airtable for NoRent.org.  **Update:** Airtable content can now be localized thanks to #1392 and #1400.

- [x] Make sure we're setting the `lang` on the `<html>` element of the page properly too. **Update:** did this in #1373.

- [x] Actually internationalize all strings on the Django side
  - [x] All validation errors, safe mode UI (#1476)
  - [x] The text message sent to users when they sign up on NoRent.org (#1497)

- [x] Actually internationalize all strings on the React side:
  - [x] Primary pages (#1405)
  - [x] `letter-builder` directory (#1406)
  - [x] `start-account-or-login` directory (#1437)
  - [x] Make sure the FAQ titles are properly internationalized (#1475)
  - [x] The letter itself, and associated emails (#1496).
  - [x] Content outside of the `norent` directory (#1476).
  - [x] 404 page and network error dialog (#1489).

- [x] Ensure that the server-side rendered modals contain localized text (#1476)

- [x] Set up the project for translation on Crowdin. **Update:** I filled out the [Crowdin open source project setup request form](https://crowdin.com/page/open-source-project-setup-request) and they responded, and we have a project slot available that we can use for the TP now!

- [x] Work around a Lingui bug that makes updating localizations challenging (#1486).
 
- [x] In order to activate the translation, we need to do so in a way that ensures that we don't direct app.justfix.nyc users to the almost-entirely-untranslated Spanish locale if the user's browser indicates the user prefers Spanish (#1498).

- [x] Design and implement a user-facing way to change the locale.  Without this, the only way for a user to see the Spanish version is if their browser indicates their language preference to our server, or if they are given a direct link to the Spanish version (#1503).

## Low-priority/bonus items

- [ ] Right now the Django side can't use any of the localization data that was extracted by Lingui, but it might be nice if it could: for example, we error with "{city}, {state} doesn't seem to exist!" on the Django-side and it'd be nice if the state name could be localized, but the localization data for that is on the front-end.  Since both tools ultimately use `.po` files it'd be nice if we could just compile Lingui's `.po` into an `.mo` and Django could use it too.  (Alternatively, I suppose Django could transmit an error code instead of an error string, and the l10n could be done in the front-end, _or_ we could change the error message to say "That city and state combination doesn't seem to exist").  Either way probably not too big a deal, though.

- [x] A big downside of the current i18n solution is that we have a single Lingui message catalog that's shared across the entire project, which sadly means that app.justfix.nyc users will be loading strings for NoRent.org.  It would be nice at the very least to be able to have separate per-site message catalogs, and even better to have a solution where message catalogs are transparently split and loaded in a way that mirrors the code splitting we're already doing (there's an issue in lingui for this at https://github.com/lingui/js-lingui/issues/503 but it hasn't seen activity for a while). **Update:** Fixed by #1407!

- [x] Some of the default ids that are being assigned are really, really long, which could bloat our code size.  **Update:** Fixed by #1438!

- [x] It's possible that our extracted localization catalogs could become out-of-date from our actual code, which isn't great.  **Update:** Fixed by #1443!

- [x] It's hard to figure out what's internationalized and what's not, it'd be nice to have a tool that automatically "garbles" any internationalized content with a fake translation so it's easier to see.  **Update:** Fixed by #1468!

**Comment by toolness** [comment]
Ok, I am closing this PR now that everything's done!
