### ISSUE TITLE
Fully internationalize app.justfix.nyc.

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/tenants2#1508]
Now that we've internationalized NoRent.org (#1384), we should internationalize the rest of the platform.  This will consist of the following:

### TextIt integration

- [ ] Our `dwh` app currently looks at raw, localized TextIt strings to determine statistics about follow-up flows; we will need to fix this somehow, e.g. by also searching for the Spanish versions of the string, or using some non-locale-dependent way of identifying user choices.

- [ ] When we create a new TextIt user, we should set their locale accordingly.

- [ ] Actually internationalize all strings on all TextIt flows.

### Rent history

- [ ] Change the DHCR email to be rendered react-side like the NoRent emails are.  This will also fix #892.

### Letter of Complaint

- [ ] Determine the UX for viewing the LOC translation (likely to be similar to NoRent) and implement it.

- [ ] Consider converting the LOC letter to be rendered React-side, like the NoRent letter is; it will likely make it easier to internationalize.

### HP Action / Emergency HP Action

- [ ] Figure out how to show the user a translation of the HP Action packet, if it's possible.

- [ ] Set the user's locale for DocuSign appropriately.

### Other

- [ ] Actually internationalize all strings on the Django side.

- [ ] Actually internationalize all strings on the React side.

- [ ] Remove the Spanish-to-English locale redirector added in #1498.  (At least feature-flag it so we can develop with it disabled!)

- [ ] Develop a strategy for linking to external resources in their native language and/or English.  For instance, it would be nice if Met Council on Housing links were in English or Spanish based on the currently active locale; and if a resource is only available in English, we should ideally identify it as being in English if the user has a different locale active.

- [ ] Figure out a way to translate arbitrary user input to English for e.g. custom issues and harassment details.  Exploratory work on this is being done in #1507.

- [ ] Figure out what to do UX-wise for the "email the LOC/HP packet" feature.  For instance, do we send the email in the user's current locale?  Do we include a translation of the PDF, or only the English version?
