### ISSUE TITLE
UI updates for Oct 1

### ISSUE THREAD

**Issue by atreni** [JustFixNYC/tenants2#197]
- [x] First/Last Name separated (#205)
- [x] Issue Checklist Icons and button style to match comps (340246764504e0a8c04679ca223c28f2f1de9432 and several commits preceding it)
- [x] Radio Buttons == Bigger! (#201)
- [x] Buttons for Boroughs (9d1de76)
- [x] Larger check boxes  (#201)
- [x] Remove background buildings image from all screens (912e644a1867f8793c8090b694ce74f06914d874)
- [x] Add "!" icon next to "I'm facing an eviction" - it should also link info modal (cb537ad7c7cc0f59cff8eb4db3ab0ee5addad5d0)
- [x] Place secondary CTA under primary CTA and center (ex/ "no go back" for address validation modal and any other modals) (427ea1f)
- [ ] Separate Back/Next buttons to be closer to each end of screen

**Comment by atreni** [comment]
- [ ] Increase the size of Check boxes as well

**Comment by atreni** [comment]
- [ ] Decrease size of Issue Area Icons
- [ ] Change the color of the box once issues have been selected

![screen shot 2018-09-25 at 5 33 50 pm](https://user-images.githubusercontent.com/7797826/46044652-64737000-c0e9-11e8-86e3-41b31667a5fb.png)

![issue checklist - bathroom](https://user-images.githubusercontent.com/7797826/46044726-98e72c00-c0e9-11e8-96db-c0936771cb99.png)
